version: '3.7'
services:
  postgres-db:
    container_name: local_postgres
    image: postgres:10.5
    command: postgres -c 'max_connections=200'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: rails_test
      POSTGRES_USER: rails
      POSTGRES_PASSWORD: password

